#ifndef HTML_DATA_H
#define HTML_DATA_H

const char *html_data =
"<!DOCTYPE html><html lang='pt-BR'><head><meta charset='UTF-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>Monitor</title>"
"<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css'>"
"<script src='https://cdn.jsdelivr.net/npm/apexcharts'></script>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box;font-family:Arial,sans-serif}"
"body{background:#1a2a6c;color:#fff;padding:8px;display:flex;justify-content:center}"
".c{width:100%;max-width:900px}"
"h1{font-size:1.4rem;text-align:center;color:#64ffda;margin-bottom:4px}"
".s{color:#a0aec0;font-size:.8rem;text-align:center}"
".d{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}"
".p{background:rgba(30,41,59,.7);border-radius:8px;padding:10px;display:flex;flex-direction:column}"
".pt{font-size:.95rem;margin-bottom:8px;color:#64ffda;display:flex;align-items:center;gap:5px}"
".v{font-size:1.6rem;font-weight:bold;text-align:center;margin-bottom:8px}"
".ch{min-height:200px;width:100%;flex-grow:1}"
".gl{display:flex;justify-content:space-between;font-size:.7rem;color:#a0aec0;margin-top:4px}"
".sg{margin-top:15px;padding-top:10px;border-top:1px solid rgba(255,255,255,.1)}"
".fl{font-size:.8rem;margin-bottom:5px;color:#a0aec0}"
".fi{width:100%;padding:6px;margin-bottom:10px;border:1px solid #2d3748;border-radius:4px;background:#0f172a;color:#fff;font-size:.9rem}"
".btn{width:100%;padding:8px;background:#4299e1;color:#fff;border:none;border-radius:4px;cursor:pointer;font-size:.9rem;margin-top:5px}"
".btn:hover{background:#3182ce}"
".lup{font-size:.65rem;color:#a0aec0;text-align:right;padding:5px 0 0;margin-top:10px;border-top:1px solid rgba(255,255,255,.1)}"
"@media(max-width:480px){.d{grid-template-columns:1fr}}"
"</style>"
"</head>"
"<body>"
"<div class='c'><header><h1>Monitor Ambiental</h1><p class='s'>Temp, Humidade, Pressão & Altitude</p></header>"
"<div class='d'>"
"<div class='p'><div class='pt'><i class='fas fa-thermometer-half'></i> Temperatura</div><div class='v' id='cT'>--.-°C</div><div id='tC' class='ch'></div><div class='gl'><span id='minTL'>Min:--.-°C</span><span id='maxTL'>Max:--.-°C</span></div>"
"<div class='sg'><div class='fl'>Min. Temp. (°C)</div><input type='number' id='minTI' step='0.1' class='fi'>"
"<div class='fl'>Máx. Temp. (°C)</div><input type='number' id='maxTI' step='0.1' class='fi'>"
"<div class='fl'>Offset Temp. (°C)</div><input type='number' id='offTI' step='0.1' class='fi'>"
"<button class='btn' onclick='SL()'>Salvar</button></div></div>"

"<div class='p'><div class='pt'><i class='fas fa-tint'></i> Humidade</div><div class='v' id='cH'>--.-%</div><div id='hC' class='ch'></div><div class='gl'><span id='minHL'>Min:--.-%</span><span id='maxHL'>Max:--.-%</span></div>"
"<div class='sg'><div class='fl'>Min. Hum. (%)</div><input type='number' id='minHI' step='0.1' class='fi'>"
"<div class='fl'>Máx. Hum. (%)</div><input type='number' id='maxHI' step='0.1' class='fi'>"
"<button class='btn' onclick='SL()'>Salvar</button></div></div>"

"<div class='p'><div class='pt'><i class='fas fa-wind'></i> Pressão</div><div class='v' id='cP'>----.-hPa</div><div id='pC' class='ch'></div><div class='gl'><span id='minPL'>Min:----.-hPa</span><span id='maxPL'>Max:----.-hPa</span></div>"
"<div class='sg'><div class='fl'>Min. Pressão (hPa)</div><input type='number' id='minPI' step='0.1' class='fi'>"
"<div class='fl'>Máx. Pressão (hPa)</div><input type='number' id='maxPI' step='0.1' class='fi'>"
"<button class='btn' onclick='SL()'>Salvar</button></div></div>"

"<div class='p'><div class='pt'><i class='fas fa-mountain'></i> Altitude</div><div class='v' id='cA'>----.-m</div></div>" // Sem chart-container
"<div class='lup' id='ts'></div>"
"</div>"
"<script>"
"const S={t:0,h:0,p:0,a:0,min_t:-20,max_t:60,off_t:0,min_h:0,max_h:100,min_p:600,max_p:1500};"
"const D={minTI:0,maxTI:0,offTI:0,minHI:0,maxHI:0,minPI:0,maxPI:0};let L={};let GDI; "
"let tC,hC,pC;const M=20;const cd={t:[],h:[],p:[]};" // cd.a removido
"function cCh(s,o){const ch=new ApexCharts(document.querySelector(s),o);ch.render();return ch;}"
"function iCh(){"
"const co={chart:{height:200,type:'line',animations:{enabled:true,easing:'linear',dynamicAnimation:{speed:1000}},toolbar:{show:false},zoom:{enabled:false}},stroke:{curve:'smooth',width:2},theme:{mode:'dark'},tooltip:{theme:'dark',x:{format:'HH:mm:ss'}},xaxis:{type:'datetime',range:M*5000,labels:{style:{colors:'#a0aec0'},datetimeUTC:false,formatter:v=>new Date(v).toLocaleTimeString('pt-BR')}},grid:{borderColor:'#2d3748'},legend:{labels:{colors:'#a0aec0'}},yaxis:{labels:{style:{colors:'#a0aec0'}}}};"
"tC=cCh('#tC',{...co,series:[{name:'Temp (°C)',data:[]}],yaxis:{min:-50,max:150,title:{text:'°C',style:{color:'#a0aec0'}}}});" // Temp -50 a 150
"hC=cCh('#hC',{...co,series:[{name:'Umd (%)',data:[]}],yaxis:{min:0,max:100,title:{text:'%',style:{color:'#a0aec0'}}}});" // Umd 0 a 100
"pC=cCh('#pC',{...co,series:[{name:'Pres (hPa)',data:[]}],yaxis:{min:900,max:1100,title:{text:'hPa',style:{color:'#a0aec0'}}}});" // Pressão 900 a 1100 (valores típicos)
"}"
"function uCh(dt){"
"const ts=new Date().getTime();const pd=(s,v)=>{s.push([ts,v]);if(s.length>M)s.shift();};"
"pd(cd.t,dt.t);pd(cd.h,dt.h);pd(cd.p,dt.p);" // cd.a removido
"tC.updateSeries([{data:cd.t}]);hC.updateSeries([{data:cd.h}]);pC.updateSeries([{data:cd.p}]);"
"}"
"function U(id,v,u){let el=document.getElementById(id);if(!el)return;el.textContent=v.toFixed(1)+u;}" 
"function UI(){"
"U('cT',S.t,'°C');U('minTL',S.min_t,'°C');U('maxTL',S.max_t,'°C');"
"U('cH',S.h,'%');U('minHL',S.min_h,'%');U('maxHL',S.max_h,'%');"
"U('cP',S.p,'hPa');U('minPL',S.min_p,'hPa');U('maxPL',S.max_p,'hPa');"
"U('cA',S.a,'m');"
"document.getElementById('ts').textContent='Atualizado: '+new Date().toLocaleTimeString('pt-BR');"
"if(!D.minTI)document.getElementById('minTI').value=S.min_t; if(!D.maxTI)document.getElementById('maxTI').value=S.max_t; if(!D.offTI)document.getElementById('offTI').value=S.off_t;"
"if(!D.minHI)document.getElementById('minHI').value=S.min_h; if(!D.maxHI)document.getElementById('maxHI').value=S.max_h;"
"if(!D.minPI)document.getElementById('minPI').value=S.min_p; if(!D.maxPI)document.getElementById('maxPI').value=S.max_p;"
"uCh(S);}"
"function VL(){" 
"S.min_t=parseFloat(document.getElementById('minTI').value); S.max_t=parseFloat(document.getElementById('maxTI').value); S.off_t=parseFloat(document.getElementById('offTI').value);"
"S.min_h=parseFloat(document.getElementById('minHI').value); S.max_h=parseFloat(document.getElementById('maxHI').value);"
"S.min_p=parseFloat(document.getElementById('minPI').value); S.max_p=parseFloat(document.getElementById('maxPI').value);"
"if(S.min_t>S.max_t)S.min_t=S.max_t; if(S.max_t<S.min_t)S.max_t=S.min_t;"
"if(S.min_h>S.max_h)S.min_h=S.max_h; if(S.max_h<S.min_h)S.max_h=S.min_h;"
"if(S.min_p>S.max_p)S.min_p=S.max_p; if(S.max_p<S.min_p)S.max_p=S.min_p;"
"UI();}"
"function SL(){"
"VL(); "
"const cL={min_temperature:S.min_t,max_temperature:S.max_t,offset_temperature:S.off_t,min_humidity:S.min_h,max_humidity:S.max_h,min_pressure:S.min_p,max_pressure:S.max_p};"
"let ch=false;for(let k in cL)if(Math.abs(cL[k]-L[k])>0.01){ch=true;break;}"
"if(!ch){GD();return;}" 
"fetch('/limites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cL)})"
".then(r=>{if(r.ok){L={...cL};GD();" 
"}else console.error('E!',r.status);}).catch(e=>console.error('E:',e));}"
"async function GD(){"
"try{const r=await fetch('/estado');const d=await r.json();"
"if(!D.minTI)S.min_t=parseFloat(d.min_temperature);"
"if(!D.maxTI)S.max_t=parseFloat(d.max_temperature);"
"if(!D.offTI)S.off_t=parseFloat(d.offset_temperature);"
"if(!D.minHI)S.min_h=parseFloat(d.min_humidity);"
"if(!D.maxHI)S.max_h=parseFloat(d.max_humidity);"
"if(!D.minPI)S.min_p=parseFloat(d.min_pressure);"
"if(!D.maxPI)S.max_p=parseFloat(d.max_pressure);"
"S.t=parseFloat(d.temperature);S.h=parseFloat(d.humidity);S.p=parseFloat(d.pressure);S.a=parseFloat(d.altitude);"
"UI();}catch(e){console.error('E:',e);}}"
"function SetupF(id,prop){" 
"const el=document.getElementById(id);if(!el)return;"
"el.addEventListener('focus',()=>{clearInterval(GDI);D[id]=1;});" 
"el.addEventListener('blur',()=>{D[id]=0;GDI=setInterval(GD,2000);GD();});" 
"el.addEventListener('change',()=>VL());" 
"}"
"function InitA(){"
"L={min_temperature:S.min_t,max_temperature:S.max_t,offset_temperature:S.off_t,min_humidity:S.min_h,max_humidity:S.max_h,min_pressure:S.min_p,max_pressure:S.max_p};"
"iCh();"
"SetupF('minTI','min_t');SetupF('maxTI','max_t');SetupF('offTI','off_t');"
"SetupF('minHI','min_h');SetupF('maxHI','max_h');"
"SetupF('minPI','min_p');SetupF('maxPI','max_p');"
"GD();GDI=setInterval(GD,2000);}"
"document.addEventListener('DOMContentLoaded',InitA);"
"</script>"
"</body>"
"</html>";

#endif // HTML_DATA_H