#ifndef HTML_DATA_H
#define HTML_DATA_H

const char *html_data =
"<!DOCTYPE html>"
"<html lang='pt-BR'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Monitor Ambiental</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box;font-family:Arial,sans-serif;}"
"body{background:#1a2a6c;color:#fff;padding:10px;display:flex;justify-content:center;}"
".container{width:100%;max-width:900px;}"
"header{text-align:center;margin:0 0 15px;}"
"h1{font-size:1.4rem;color:#64ffda;margin-bottom:5px;}"
".dashboard{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px;}"
".panel{background:rgba(30,41,59,0.7);border-radius:8px;padding:12px;}"
".panel-title{font-size:1rem;margin-bottom:10px;color:#64ffda;}"
".gauge{height:100px;position:relative;margin:10px 0;}"
".gauge-bg{height:20px;background:#0f172a;border-radius:10px;border:1px solid #2c5282;}"
".gauge-fill{height:100%;border-radius:10px;background:linear-gradient(90deg,#00bfff,#1e90ff);width:0;}"
".gauge-value{position:absolute;top:-25px;font-size:1.5rem;font-weight:bold;}"
".gauge-minmax{display:flex;justify-content:space-between;margin-top:5px;font-size:0.75rem;}"
".slider-container{margin:15px 0 5px;position:relative;}"
"input[type='range']{width:100%;height:5px;background:#2d3748;border-radius:2px;}"
"input[type='range']::-webkit-slider-thumb{-webkit-appearance:none;width:16px;height:16px;border-radius:50%;background:#4299e1;}"
".slider-value{position:absolute;top:-20px;left:50%;transform:translateX(-50%);font-size:0.8rem;background:rgba(15,23,42,0.9);padding:2px 8px;border-radius:8px;}"
".min-value{color:#4ade80;}"
".max-value{color:#ff6b6b;}"
".last-update{text-align:right;font-size:0.7rem;color:#a0aec0;margin-top:10px;}"
"@media(max-width:600px){.dashboard{grid-template-columns:1fr;}}"
"</style>"
"</head>"
"<body>"
"<div class='container'>"
"<header><h1>Monitor Ambiental</h1></header>"
"<div class='dashboard'>"
"<div class='panel'>"
"<div class='panel-title'>Temperatura</div>"
"<div class='gauge'><div class='gauge-value' id='tempValue'>0°C</div><div class='gauge-bg'><div class='gauge-fill' id='tempFill'></div></div><div class='gauge-minmax'><span id='tempMin'>0°C</span><span id='tempMax'>0°C</span></div></div>"
"<div class='slider-container'><input type='range' id='minTemp' min='-10' max='50' step='0.5'><div class='slider-value min-value' id='minTempValue'>0°C</div></div>"
"<div class='slider-container'><input type='range' id='maxTemp' min='-10' max='50' step='0.5'><div class='slider-value max-value' id='maxTempValue'>0°C</div></div>"
"<div class='slider-container'><input type='range' id='offsetTemp' min='-5' max='5' step='0.1'><div class='slider-value' id='offsetTempValue'>0°C</div></div>"
"</div>"
"<div class='panel'>"
"<div class='panel-title'>Umidade</div>"
"<div class='gauge'><div class='gauge-value' id='humValue'>0%</div><div class='gauge-bg'><div class='gauge-fill' id='humFill'></div></div><div class='gauge-minmax'><span id='humMin'>0%</span><span id='humMax'>0%</span></div></div>"
"<div class='slider-container'><input type='range' id='minHum' min='0' max='100' step='1'><div class='slider-value min-value' id='minHumValue'>0%</div></div>"
"<div class='slider-container'><input type='range' id='maxHum' min='0' max='100' step='1'><div class='slider-value max-value' id='maxHumValue'>0%</div></div>"
"</div>"
"<div class='panel'>"
"<div class='panel-title'>Pressão</div>"
"<div class='gauge'><div class='gauge-value' id='presValue'>0hPa</div><div class='gauge-bg'><div class='gauge-fill' id='presFill'></div></div><div class='gauge-minmax'><span id='presMin'>0hPa</span><span id='presMax'>0hPa</span></div></div>"
"<div class='slider-container'><input type='range' id='minPres' min='900' max='1100' step='1'><div class='slider-value min-value' id='minPresValue'>0hPa</div></div>"
"<div class='slider-container'><input type='range' id='maxPres' min='900' max='1100' step='1'><div class='slider-value max-value' id='maxPresValue'>0hPa</div></div>"
"</div>"
"<div class='panel'>"
"<div class='panel-title'>Altitude</div>"
"<div class='gauge'><div class='gauge-value' id='altValue'>0m</div><div class='gauge-bg'><div class='gauge-fill' id='altFill'></div></div></div>"
"</div>"
"</div>"
"<div class='last-update' id='timestamp'></div>"
"</div>"
"<script>"
"const state={"
"t:0,h:0,p:0,a:0,"
"min_t:0,max_t:0,off_t:0,"
"min_h:0,max_h:0,"
"min_p:0,max_p:0"
"};"
"let lastSent={};"
"function updateUI(){"
"document.getElementById('tempValue').textContent=state.t.toFixed(1)+'°C';"
"document.getElementById('humValue').textContent=state.h.toFixed(0)+'%';"
"document.getElementById('presValue').textContent=state.p.toFixed(1)+'hPa';"
"document.getElementById('altValue').textContent=state.a.toFixed(1)+'m';"
"document.getElementById('tempMin').textContent=state.min_t.toFixed(1)+'°C';"
"document.getElementById('tempMax').textContent=state.max_t.toFixed(1)+'°C';"
"document.getElementById('humMin').textContent=state.min_h+'%';"
"document.getElementById('humMax').textContent=state.max_h+'%';"
"document.getElementById('presMin').textContent=state.min_p+'hPa';"
"document.getElementById('presMax').textContent=state.max_p+'hPa';"
"document.getElementById('tempFill').style.width=((state.t+10)/60*100)+'%';"
"document.getElementById('humFill').style.width=state.h+'%';"
"document.getElementById('presFill').style.width=((state.p-900)/200*100)+'%';"
"document.getElementById('altFill').style.width=(Math.min(state.a,3000)/30)+'%';"
"document.getElementById('minTempValue').textContent=state.min_t.toFixed(1)+'°C';"
"document.getElementById('maxTempValue').textContent=state.max_t.toFixed(1)+'°C';"
"document.getElementById('offsetTempValue').textContent=state.off_t.toFixed(1)+'°C';"
"document.getElementById('minHumValue').textContent=state.min_h+'%';"
"document.getElementById('maxHumValue').textContent=state.max_h+'%';"
"document.getElementById('minPresValue').textContent=state.min_p+'hPa';"
"document.getElementById('maxPresValue').textContent=state.max_p+'hPa';"
"document.getElementById('timestamp').textContent='Atualizado: '+new Date().toLocaleTimeString();}"
"function sendLimits(){"
"if(JSON.stringify(lastSent)==JSON.stringify({"
"min_t:state.min_t,max_t:state.max_t,off_t:state.off_t,"
"min_h:state.min_h,max_h:state.max_h,"
"min_p:state.min_p,max_p:state.max_p}))return;"
"fetch('/limites',{"
"method:'POST',"
"headers:{'Content-Type':'application/json'},"
"body:JSON.stringify({"
"min_temperature:state.min_t,"
"max_temperature:state.max_t,"
"offset_temperature:state.off_t,"
"min_humidity:state.min_h,"
"max_humidity:state.max_h,"
"min_pressure:state.min_p,"
"max_pressure:state.max_p"
"})"
"}).then(r=>{if(r.ok)lastSent={...state};});}"
"async function getData(){"
"try{"
"const r=await fetch('/estado');"
"const d=await r.json();"
"state.t=d.temperature;"
"state.h=d.humidity;"
"state.p=d.pressure;"
"state.a=d.altitude;"
"state.min_t=d.min_temperature;"
"state.max_t=d.max_temperature;"
"state.off_t=d.offset_temperature;"
"state.min_h=d.min_humidity;"
"state.max_h=d.max_humidity;"
"state.min_p=d.min_pressure;"
"state.max_p=d.max_pressure;"
"updateUI();"
"}catch(e){}}"
"function init(){"
"document.getElementById('minTemp').addEventListener('input',e=>{state.min_t=parseFloat(e.target.value);updateUI();});"
"document.getElementById('maxTemp').addEventListener('input',e=>{state.max_t=parseFloat(e.target.value);updateUI();});"
"document.getElementById('offsetTemp').addEventListener('input',e=>{state.off_t=parseFloat(e.target.value);updateUI();});"
"document.getElementById('minHum').addEventListener('input',e=>{state.min_h=parseInt(e.target.value);updateUI();});"
"document.getElementById('maxHum').addEventListener('input',e=>{state.max_h=parseInt(e.target.value);updateUI();});"
"document.getElementById('minPres').addEventListener('input',e=>{state.min_p=parseInt(e.target.value);updateUI();});"
"document.getElementById('maxPres').addEventListener('input',e=>{state.max_p=parseInt(e.target.value);updateUI();});"
"const sliders=document.querySelectorAll('input[type=range]');"
"sliders.forEach(s=>s.addEventListener('change',sendLimits));"
"getData();"
"setInterval(getData,2000);}"
"document.addEventListener('DOMContentLoaded',init);"
"</script>"
"</body>"
"</html>";

#endif // HTML_DATA_H